config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :activities do
    member do 
      put '/update_status' => 'activities#update_status'
    end
  end
  # get 'home/index'
  root 'home#index'
  get '/about', to: 'home#about',  as: 'about'
  put '/update_status_inprogress/:id', to: 'activities#update_status_inprogress',  as: 'update_status_inprogress'
  put '/update_status_done/:id', to: 'activities#update_status_done',  as: 'update_status_done'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy update_status]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_status
    @activity.update(type_activity: params[:type_activity])
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:type_activity, :title, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/activities/_activity.html.erb
<div class="container">
  <div id="<%= dom_id activity %>">
    <p>
      <strong>Type activity:</strong>
      <%= activity.type_activity %>
    </p>

    <p>
      <strong>Title:</strong>
      <%= activity.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= activity.description %>
    </p>

  </div>
</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :type_activity, style: "display: block" %>
    <%= form.select  :type_activity, ["Backlog", "In progress", "Done"], :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, :class => "form-control" %>
  </div>

  <div class="mt-3">
    <%= form.submit 'submit', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<div class="container">
  <%= render HeaderComponent.new(title: "Editing Activity")%>

  <%= render "form", activity: @activity %>

  <br>

  <div>
    <%= link_to "Show this activity", @activity %> |
    <%= link_to "Back to activities", activities_path %>
  </div>
</div>

app/views/activities/index.html.erb
<%= render NotifComponent.new(notice: notice)%>

<%= render HeaderComponent.new(title: "Activities")%>

<div id="activities">
  <div class="container">
      <div class="row">
        <div class="col-sm-4 ">
          <%= render CardTodoListComponent.new(activities: @activities, progres_type: "Backlog", background_color: "bg-secondary")%>
        </div>
        <div class="col-sm-4 ">
            <%= render CardTodoListComponent.new(activities: @activities, progres_type: "In progress", background_color: "bg-primary")%>
        </div>
        <div class="col-sm-4 ">
          <%= render CardTodoListComponent.new(activities: @activities, progres_type: "Done", background_color: "bg-success")%>
        </div>  
      </div>
    </div>
  </div>
</div>

<div class="container mt-5">
  <center>
    <%= link_to "New activity", new_activity_path, :class => "btn btn-success" %>
  </center>
</div>

<%= javascript_include_tag "todo_list" %>

app/views/activities/new.html.erb
<div class="container">
  <%= render HeaderComponent.new(title: "New Activity")%>

  <%= render "form", activity: @activity %>

  <br>

  <div>
    <%= link_to "Back to activities", activities_path %>
  </div>
</div>

app/views/activities/show.html.erb
<div class="container">
  <%= render NotifComponent.new(notice: notice)%>

  <%= render HeaderComponent.new(title: "Show Activity")%>

  <%= render @activity %>

  <div>
    <%= link_to "Edit this activity", edit_activity_path(@activity) %> |
    <%= link_to "Back to activities", activities_path %>

    <div class="mt-3">
      <%= button_to "Destroy this activity", @activity, method: :delete, :class => "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/home/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-white text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <div>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-github"></i>
      </a>
    </div>
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3 text-secondary"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3 text-secondary"></i> Denpasar, Bali, ID</p>
          <p>
            <i class="fas fa-envelope me-3 text-secondary"></i>
            amertakurnia@gmail.com
          </p>
          <p><i class="fas fa-phone me-3 text-secondary"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4 bg-dark">
    © 2021 Copyright
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Home", '/', :class => "navbar-brand" %>
    <%# <a class="navbar-brand" href="#">Home</a> %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <%= link_to "About", about_path, :class => "nav-link" %>
                <%# <a class="nav-link" href="#">About <span class="sr-only">(current)</span></a> %>
            </li>
        </ul>
        <% if current_user %>
            <form method="DELETE" action="/users/sign_out" class="form-inline my-2 my-lg-0">
                <button class="btn btn-danger my-2 my-sm-0" type="submit">Log out</button>
            </form>
        <% end %>
    </div>
</nav>

app/views/home/about.html.erb
<div class="container">
    <%= render HeaderComponent.new(title: "About Todo List") %>
    <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel felis accumsan, consequat dui sodales, congue tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce arcu magna, laoreet et est a, porta volutpat mauris. Mauris interdum non sem vitae suscipit. Vivamus aliquet consectetur leo a sodales. Morbi vel quam eu ante dignissim porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ac tempus tortor, vitae ullamcorper neque. Nullam vulputate nisl a orci egestas iaculis.
    </p>
    <p>
    Nulla laoreet non ante vitae facilisis. Morbi malesuada pretium tincidunt. Mauris eu risus at libero bibendum lobortis. Curabitur ac leo ac purus viverra finibus. Cras mattis, ligula vitae pulvinar vehicula, dui quam venenatis metus, sed ornare orci odio ac nulla. Ut vel dignissim neque. Vivamus orci tortor, mollis a iaculis eu, dictum a elit. Mauris vel mi nibh. Vivamus rutrum ultrices lobortis.
    </p>
    <p>
    Vestibulum congue ornare feugiat. Phasellus vitae porta ex. Sed non urna gravida, placerat eros eget, consectetur enim. Duis et mauris sed ex imperdiet commodo. Integer in fringilla lacus. Vivamus augue diam, bibendum nec felis a, vehicula egestas sem. Maecenas a vestibulum mi. Vestibulum et tempor sem, vitae egestas ex. Aliquam varius nisi sagittis erat euismod finibus. Phasellus et purus velit. Mauris scelerisque diam malesuada urna condimentum eleifend. Pellentesque euismod varius ante at ultricies.
    </p>
    <p>
    Phasellus at malesuada mauris, at ornare neque. Sed fringilla, diam eget posuere efficitur, nisi libero ornare metus, varius lobortis elit libero at lectus. In posuere lacus at dolor molestie fringilla. Cras eget maximus turpis, et pellentesque nibh. Vivamus eu urna tincidunt, fringilla nulla a, cursus nisi. Nulla maximus purus vitae porttitor tincidunt. Phasellus ullamcorper malesuada nisl sit amet congue. Nullam rutrum augue vitae erat ultricies, a luctus nunc accumsan. Ut aliquam sodales ex a mollis. Aliquam id ante quam. In porttitor odio tincidunt, aliquam erat et, malesuada orci. Donec vehicula semper consectetur. Nulla consequat orci a molestie mollis. Praesent viverra sapien placerat nisl egestas dictum.
    </p>
    <p>
    Integer non tincidunt felis, a ullamcorper velit. Sed at ante consequat, pretium ipsum id, accumsan libero. Sed vehicula turpis sit amet nunc lobortis dictum. Fusce tristique et est quis blandit. Sed ullamcorper, mi vitae porttitor egestas, ex mauris facilisis nisl, ut efficitur dolor nunc et enim. Donec bibendum pharetra ultrices. In commodo faucibus leo in suscipit. Curabitur dignissim nec dui sed cursus. Aliquam vitae sapien imperdiet, ultrices nisi eu, vulputate velit. Vivamus ut malesuada sem. Maecenas facilisis tempus ante, quis vulputate nibh. Curabitur purus orci, imperdiet a neque sed, vehicula dictum purus. Quisque non nisi in massa sollicitudin consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut rutrum in libero at varius.
    </p>
<div>

app/views/home/index.html.erb
<%= render NotifComponent.new(notice: notice)%>

<%= render HeaderComponent.new(title: "Todo List")%>

<div class="container">
    <center>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum dictum est, a pharetra lectus lacinia a. Morbi dapibus lacinia tortor, eu lacinia urna euismod vel. Nam rutrum ligula vel odio blandit lobortis. Phasellus vitae magna nec sapien ultricies vehicula vitae non leo. Praesent finibus dolor pharetra dictum sollicitudin. Donec varius luctus tellus id ornare. Suspendisse efficitur accumsan massa. Cras at risus vitae nisl eleifend molestie et vitae magna. Ut varius tempus accumsan. Ut blandit porttitor sodales. Mauris nec enim dapibus, placerat enim fringilla, interdum tellus. Proin pretium leo et facilisis condimentum. Curabitur et sapien nulla. Etiam tincidunt hendrerit justo sed pretium. Nullam dapibus quam in euismod feugiat.
        </p>
    </center>
    <div class="container mt-5">
        <center>
            <%= link_to "Show Activity", activities_path, :class => "btn btn-success" %>
        </center>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header'%>
    <%= yield %>
    <%= render 'home/footer'%>
  </body>
</html>